version: "2"

services:
  notato:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - /mnt/wisconsin/flexo:/data
      - .:/code/
      - /code/node_modules/
